//! Search-related wire messages.
//!
//! Wave-7 web parity: the desktop binary spawns `rg`, `fff_search::FilePicker`,
//! and `git status --porcelain` directly. The web frontend cannot, so the
//! daemon runs those tools on its host and streams the hits back over the
//! WebSocket. The POD hit shapes here intentionally mirror
//! `neoism_ui::services::{SearchFileHit, SearchGrepHit, SearchGitHit}` so the
//! daemon-side `SearchService` impl can hand the protocol structs straight to
//! the panel without translating field-by-field.
//!
//! Each request carries a `req_id` (`u64`) generated by the client. The server
//! tags every reply — including incremental `SearchProgress` and terminal
//! `SearchError` frames — with the same id so the host can route the reply
//! back to the originating `IoError::Pending(req_id)` call.

use serde::{Deserialize, Serialize};

/// Correlation id for matching server replies back to the originating
/// `SearchService` call. Matches `neoism_ui::services::RequestId`.
pub type RequestId = u64;

/// File-search mode. Mirrors `neoism_ui::services::SearchFileMode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SearchFileMode {
    Fuzzy,
    Exact,
}

/// Grep-search mode. Mirrors `neoism_ui::services::SearchGrepMode`. Regex
/// is folded into the mode enum (not a separate boolean) to stay in lock-step
/// with the trait.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SearchGrepMode {
    Fuzzy,
    Exact,
    Regex,
}

/// Git porcelain status group for a single changed file. Mirrors
/// `neoism_ui::services::SearchGitStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SearchGitStatus {
    Modified,
    Staged,
    Mixed,
    Added,
    Deleted,
    Renamed,
    Untracked,
    Conflict,
}

/// One scored file path. Field-for-field mirror of
/// `neoism_ui::services::SearchFileHit`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchFileHit {
    pub score: i32,
    pub path: String,
}

/// One scored directory path. Field-for-field mirror of
/// `neoism_ui::services::SearchDirectoryHit`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchDirectoryHit {
    pub score: i32,
    pub path: String,
}

/// One scored grep match. Field-for-field mirror of
/// `neoism_ui::services::SearchGrepHit`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchGrepHit {
    pub score: i32,
    pub path: String,
    pub line: u32,
    pub column: u32,
    pub text: String,
}

/// One row in the git-changes finder. Field-for-field mirror of
/// `neoism_ui::services::SearchGitHit`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchGitHit {
    pub path: String,
    pub status: SearchGitStatus,
    pub line: u32,
    pub text: String,
}

/// Client → Server. `cwd` is workspace-relative; the daemon rejects `..`
/// traversal and absolute paths via `SearchServerMessage::Error`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SearchClientMessage {
    /// `rg --files` rooted at `cwd`; relative paths. Maps to
    /// `SearchService::collect_files`.
    CollectFiles { req_id: RequestId, cwd: String },
    /// Fuzzy / exact file picker over `cwd`. Maps to
    /// `SearchService::search_files`.
    SearchFiles {
        req_id: RequestId,
        query: String,
        cwd: String,
        mode: SearchFileMode,
    },
    /// Fuzzy directory-only search over `cwd`. Maps to
    /// `SearchService::search_directories`.
    SearchDirectories {
        req_id: RequestId,
        query: String,
        cwd: String,
    },
    /// `rg <query>` (or fuzzy / regex variant) rooted at `cwd`. Maps to
    /// `SearchService::search_grep`.
    ///
    /// `case_sensitive` and `file_patterns` are optional refinements the
    /// daemon-side ripgrep wrapper can honour; the trait itself does not
    /// expose them, so panels supply `None` / empty by default. They live
    /// on the wire so we don't have to bump the message shape later.
    SearchGrep {
        req_id: RequestId,
        query: String,
        cwd: String,
        mode: SearchGrepMode,
        case_sensitive: Option<bool>,
        file_patterns: Vec<String>,
    },
    /// `git status --porcelain=v1 -z` parsed into change rows for the repo
    /// containing `cwd`. Maps to `SearchService::collect_git_changes`.
    SearchGitChanges { req_id: RequestId, cwd: String },
    /// Resolve `git rev-parse --show-toplevel` for `cwd`. Maps to
    /// `SearchService::git_repo_root`.
    GitRepoRoot { req_id: RequestId, cwd: String },
    /// Best-effort cancel for an in-flight request. The server stops the
    /// underlying `rg` / `git` process (if still running) and either drops
    /// the reply or sends `SearchError { req_id, message: "cancelled" }`.
    CancelSearch { req_id: RequestId },
}

/// Server → Client. Every variant carries the originating `req_id`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SearchServerMessage {
    /// Reply to `CollectFiles`. `paths` are `cwd`-relative.
    CollectFilesResult {
        req_id: RequestId,
        paths: Vec<String>,
    },
    /// Reply to `SearchFiles`.
    SearchFilesResult {
        req_id: RequestId,
        hits: Vec<SearchFileHit>,
    },
    /// Reply to `SearchDirectories`.
    SearchDirectoriesResult {
        req_id: RequestId,
        hits: Vec<SearchDirectoryHit>,
    },
    /// Reply to `SearchGrep`.
    SearchGrepResult {
        req_id: RequestId,
        hits: Vec<SearchGrepHit>,
    },
    /// Reply to `SearchGitChanges`.
    SearchGitChangesResult {
        req_id: RequestId,
        hits: Vec<SearchGitHit>,
    },
    /// Reply to `GitRepoRoot`. `None` when `cwd` is not inside a git repo.
    GitRepoRootResult {
        req_id: RequestId,
        path: Option<String>,
    },
    /// Optional incremental progress frame the daemon can push while a
    /// long-running `rg` is still streaming. `found_so_far` is a running
    /// count of hits produced for this `req_id`. The terminal
    /// `Search*Result` frame still arrives at the end.
    SearchProgress {
        req_id: RequestId,
        found_so_far: u64,
    },
    /// Terminal error for `req_id`. No further frames will be sent for it.
    SearchError { req_id: RequestId, message: String },
}
