#!/usr/bin/env python3
"""Regenerate Neoism's bundled themes from an NvChad/base46 checkout."""

import argparse
import pathlib
import shutil
import subprocess
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "neoism-frontend/shared/src/primitives/nvchad_themes.rs"
DEFAULT_REF = "v3.0"

LUA = r'''
package.preload["base46"] = function()
  return { override_theme = function(theme) return theme end }
end
package.preload["nvconfig"] = function()
  return {
    base46 = { transparency = false },
    ui = {
      telescope = { style = "bordered" },
      cmp = { style = "default" },
      statusline = { theme = "default" },
    },
  }
end

local fields30 = {
  "black", "white", "one_bg", "one_bg2", "line", "grey_fg",
  "light_grey", "pmenu_bg", "folder_bg", "red", "green", "yellow",
  "blue", "purple", "cyan", "darker_black",
}
local fields16 = {
  "base0B", "base09", "base0E", "base0E", "base0D", "base0A",
  "base08", "base0C", "base0F",
}

for file in io.popen("find " .. string.format("%q", arg[1]) .. " -maxdepth 1 -name '*.lua' | sort"):lines() do
  local name = file:match("([^/]+)%.lua$")
  local ok, theme = pcall(dofile, file)
  if not ok then error(name .. ": " .. tostring(theme)) end
  local values = {}
  for _, key in ipairs(fields30) do table.insert(values, theme.base_30[key]) end
  table.insert(values, theme.base_30.grey_fg) -- comments follow Base46 treesitter.lua
  for _, key in ipairs(fields16) do table.insert(values, theme.base_16[key]) end
  for index, value in ipairs(values) do
    if type(value) ~= "string" or not value:match("^#%x%x%x%x%x%x$") then
      error(name .. ": invalid/missing mapped color " .. index .. " (" .. tostring(value) .. ")")
    end
  end
  io.write(name, "\t", table.concat(values, "\t"), "\n")
end
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=pathlib.Path, help="existing base46 checkout")
    parser.add_argument("--ref", default=DEFAULT_REF, help="base46 git ref to snapshot")
    args = parser.parse_args()

    if not shutil.which("lua"):
        raise SystemExit("lua is required to evaluate Base46 theme modules")

    temp = None
    source = args.source
    if source is None:
        temp = tempfile.TemporaryDirectory(prefix="neoism-base46-")
        source = pathlib.Path(temp.name)
        subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", args.ref,
             "https://github.com/NvChad/base46.git", str(source)],
            check=True,
        )

    themes_dir = source / "lua/base46/themes"
    result = subprocess.run(
        ["lua", "-", str(themes_dir)],
        input=LUA,
        text=True,
        capture_output=True,
        check=True,
    )
    rows = []
    for line in result.stdout.splitlines():
        name, *colors = line.split("\t")
        if len(colors) != 26:
            raise SystemExit(f"{name}: expected 26 mapped colors, got {len(colors)}")
        packed = "".join(color[1:].lower() for color in colors)
        rows.append(f'    ("{name}", "{packed}"),')

    revision = subprocess.run(
        ["git", "-C", str(source), "rev-parse", "HEAD"],
        text=True,
        capture_output=True,
        check=True,
    ).stdout.strip()
    output = "\n".join([
        "// @generated by scripts/update-nvchad-themes.py; do not edit by hand.",
        "// Base46 is MIT licensed; see THIRD_PARTY_LICENSES/NvChad-base46.txt.",
        "#[allow(dead_code)]",
        f'pub const BASE46_REVISION: &str = "{revision}";',
        "pub const THEMES: &[(&str, &str)] = &[",
        *rows,
        "];",
        "",
    ])
    OUTPUT.write_text(output)
    print(f"wrote {len(rows)} themes to {OUTPUT.relative_to(ROOT)} at {revision[:12]}")


if __name__ == "__main__":
    main()